#!/usr/bin/python3
import tkinter as tk
import subprocess
import sys

class SplashScreen:
    def __init__(self, root):
        self.root = root
        self.root.title("Administrator Authorization")
        self.root.geometry("300x100")
        
        self.label = tk.Label(root, text="Enter your administrator password:")
        self.label.pack(pady=5)
        
        self.password_entry = tk.Entry(root, show="*")
        self.password_entry.pack(pady=5)
        self.password_entry.bind("<Return>", self.submit_password)  # Bind the <Return> key event
        self.submit_button = tk.Button(root, text="Submit", command=self.submit_password)
        self.submit_button.pack(pady=5)

    def submit_password(self, event=None):
        # Get the entered password
        entered_password = self.password_entry.get()
        
        # Execute a command that requires administrator privileges
        command = f"echo '{entered_password}' | sudo -S echo 'Password accepted'"
        process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, error = process.communicate()
        
        # Check if the command was successful
        if error:
            print("Invalid Password")  # Print a message if the password is invalid
        else:
            print("Password accepted")  # Print a message if the password is accepted
            
            # Hide the splash screen
            self.root.withdraw()
            
            # Execute Large/Junk Filescan
            try:
                subprocess.Popen([sys.executable, "/bin/scandrive.py"])  #Scans for Unused/Large and Trash Files to Cleanup
            except FileNotFoundError:
                print("Trash cleanup file not found")
            
            # Execute the main script
            try:
                subprocess.Popen([sys.executable, "/bin/shredbody.py"])  # Replace ".py" with the actual name of your main script
            except FileNotFoundError:
                print("Main script not found.")

if __name__ == "__main__":
    root = tk.Tk()
    app = SplashScreen(root)
    root.mainloop()

